# Group 5
## Data Wrangling Final Project
## Social Determinants of Health

Jonathan Himes jonathan.himes@utah.edu U1367169 <br>
Michelle Kubicki michelle.kubicki@utah.edu U1370752<br> 
Yueqin Yang yueqin.yang@hsc.utah.edu U0737683<br> 
Jackie Bearnson u0763123@umail.utah.edu U0763123 <br>
Lucia Ranallo U1427138@umail.utah.edu U1427138 <br>
___

In [1]:
# Import required packages
import pandas as pd
import numpy as np
from operator import truediv

In [2]:
# Read in data
race_df = pd.read_csv('Project/Data/C02003_Detailed Race--Data.csv',skiprows=[1])
latino_df = pd.read_csv('Project/Data/B03002-Hispanic-Data.csv',skiprows=[1])
native_df = pd.read_csv('Project/Data/B99051-Native-Data.csv',index_col=0)
citizen_df = pd.read_csv('Project/Data/B05002-Citizenship-Data.csv',index_col=0)
education_df = pd.read_csv('Project/Data/S1501-Education-Data.csv',index_col=0)
english_df = pd.read_csv('Project/Data/C16001-Language-Data.csv',index_col=0)
HH_df = pd.read_csv('Project/Data/S1901-HHIncome-Data.csv',index_col=0)
unemployment_df = pd.read_csv('Project/Data/S2301-Unemployment-Data.csv',index_col=0)
insured_df = pd.read_csv('Project/Data/S2701-Insurance-Data.csv',index_col=0)
private_insurance_df = pd.read_csv('Project/Data/S2703-Private_Insurance-Data.csv',index_col=0)
public_insurance_df = pd.read_csv('Project/Data/S2704-Public_Insurance-Data.csv',index_col=0)

In [3]:
# Create Facets Df
df = pd.DataFrame()

In [4]:
# Populate Facets DF
df['FIPS'] = race_df['GEO_ID'].str[-11:] # Add FIPS Column
#df['Urban'] = # Add FIPS Column
df['Total_population'] = race_df['C02003_001E'] # Add Total Population Column
df['P_WH'] = race_df['C02003_003E']/race_df['C02003_001E'] # Add % White Column
df['P_AA'] = race_df['C02003_004E']/race_df['C02003_001E'] # Add % African-American Column
df['P_AI'] = race_df['C02003_005E']/race_df['C02003_001E'] # Add % American Indian Column
df['P_AS'] = race_df['C02003_006E']/race_df['C02003_001E'] # Add % Asian Column
df['P_NH'] = race_df['C02003_007E']/race_df['C02003_001E'] # Add % Native Hawaiian/Pacific Islander Column
df['P_OR'] = race_df['C02003_008E']/race_df['C02003_001E'] # Add % Other Race Column
df['P_2R'] = race_df['C02003_009E']/race_df['C02003_001E']# Add % 2 or more Races Column
df['P_Latino'] = latino_df['B03002_012E']/race_df['C02003_001E'] # Add % Latino/Hispanic Ethnicity Column

In [5]:
#Calculate the native born population
nb_list = []
for i in native_df.iloc[1].values:
    if isinstance(i, str):
        nb_list.append(int(i.replace(',',"")))
    else: nb_list.append(i)

# Calculate the foreign born population
fb_list = []
for i in native_df.iloc[4].values:
    if isinstance(i, str):
        fb_list.append(int(i.replace(',',"")))
    else: fb_list.append(i)
    
# Calculate the non citizens for each tract
nc_list = []
for i in citizen_df[citizen_df.columns[0::2]].iloc[20].tolist():
    if isinstance(i, str):
        nc_list.append(int(i.replace(',',"")))
    else: nc_list.append(i)
    
citizens_list = [sum(x) for x in zip(nb_list, fb_list)]
citizens_plus_noncitizens = [sum(x) for x in zip(nb_list, fb_list, nc_list)]


df['P_native'] = nb_list/race_df['C02003_001E'] # Add % Native Born Column
df['P_FB'] = fb_list/race_df['C02003_001E'] # Add % Foreign Born Column
df['P_citizen'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(citizens_list, citizens_plus_noncitizens)] # Add % Citizen Column
df['P_non-citizen'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(nc_list, citizens_plus_noncitizens)] # Add % Non Citizen Column

In [6]:
# Calculate no education less than equal 24
ne_24_list = []
for i in education_df[education_df.columns[0::12]].iloc[2].values:
    if isinstance(i, str):
        ne_24_list.append(int(i.replace(',',"")))
    else: ne_24_list.append(i)
    
# Calculate no education greater than equal 25
ne_25_list = []
for i in education_df[education_df.columns[0::12]].iloc[7].values:
    if isinstance(i, str):
        ne_25_list.append(int(i.replace(',',"")))
    else: ne_25_list.append(i)
    
# Calculate total less than equal 24
t_24_list = []
for i in education_df[education_df.columns[0::12]].iloc[1].values:
    if isinstance(i, str):
        t_24_list.append(int(i.replace(',',"")))
    else: t_24_list.append(i)
    
# Calculate total greater than equal 25
t_25_list = []
for i in education_df[education_df.columns[0::12]].iloc[6].values:
    if isinstance(i, str):
        t_25_list.append(int(i.replace(',',"")))
    else: t_25_list.append(i)
    
# Calculate total no education
total_no_education = [sum(x) for x in zip(ne_24_list, ne_25_list)]

# Calculate total population
total_population = [sum(x) for x in zip(t_24_list, t_25_list)]

# Calculate went to highscool no degree
hs_nd_list = []
for i in education_df[education_df.columns[0::12]].iloc[8].values:
    if isinstance(i, str):
        hs_nd_list.append(int(i.replace(',',"")))
    else: hs_nd_list.append(i)
    
# Calculate Completed highschool under 24
hs_c_24_list = []
for i in education_df[education_df.columns[0::12]].iloc[3].values:
    if isinstance(i, str):
        hs_c_24_list.append(int(i.replace(',',"")))
    else: hs_c_24_list.append(i)
    
# Calculate Completed highschool over 25
hs_c_25_list = []
for i in education_df[education_df.columns[0::12]].iloc[9].values:
    if isinstance(i, str):
        hs_c_25_list.append(int(i.replace(',',"")))
    else: hs_c_25_list.append(i)

# Caluclate total completed hs with degree
highschool_degree = [sum(x) for x in zip(hs_c_24_list, hs_c_25_list)]

# Calculate Completed highschool over 25
hs_c_25_list = []
for i in education_df[education_df.columns[0::12]].iloc[9].values:
    if isinstance(i, str):
        hs_c_25_list.append(int(i.replace(',',"")))
    else: hs_c_25_list.append(i)
    
# Calculate some college under 24
sc_24_list = []
for i in education_df[education_df.columns[0::12]].iloc[4].values:
    if isinstance(i, str):
        sc_24_list.append(int(i.replace(',',"")))
    else: sc_24_list.append(i)
    
# Calculate some college over 25
sc_25_list = []
for i in education_df[education_df.columns[0::12]].iloc[10].values:
    if isinstance(i, str):
        sc_25_list.append(int(i.replace(',',"")))
    else: sc_25_list.append(i)
    
# Calculate total some college
total_some_college = [sum(x) for x in zip(sc_24_list, sc_25_list)]

# Calculate college degree under 24
cd_24_list = []
for i in education_df[education_df.columns[0::12]].iloc[5].values:
    if isinstance(i, str):
        cd_24_list.append(int(i.replace(',',"")))
    else: cd_24_list.append(i)
    
# Calculate associate degree
ad_list = []
for i in education_df[education_df.columns[0::12]].iloc[11].values:
    if isinstance(i, str):
        ad_list.append(int(i.replace(',',"")))
    else: ad_list.append(i)
    
# Calculate bachelors degree
bd_list = []
for i in education_df[education_df.columns[0::12]].iloc[12].values:
    if isinstance(i, str):
        bd_list.append(int(i.replace(',',"")))
    else: bd_list.append(i)
    
# Calculate total college degree
total_college_degree = [sum(x) for x in zip(cd_24_list, ad_list, bd_list)]

# Calculate graduate degree
gd_list = []
for i in education_df[education_df.columns[0::12]].iloc[13].values:
    if isinstance(i, str):
        gd_list.append(int(i.replace(',',"")))
    else: gd_list.append(i)
    
df['P_NoSchool'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(total_no_education, total_population)] # Add % No schooling Column
df['P_HS_no_degree'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(hs_nd_list, total_population)] # Add % completed high school, no degree Column
df['P_HS_or_GED'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(highschool_degree, total_population)] # Add % High school or GED degree Column
df['P_some_college'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(total_some_college, total_population)] # Add % some college, no degree Column
df['P_college_degree'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(total_college_degree, total_population)] # Add % AA or BA Column
df['P_Masters_prof_doc'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(gd_list, total_population)] # Add % Masters, professional, doctorate Column

In [7]:
# Calculate the Percent limited english
english_df_reduced = english_df[english_df.columns[0::2]].applymap(lambda x: int(x.replace(',',"")) if isinstance(x, str) else x)
total_speakers = english_df_reduced.loc["Total:"].tolist()
english_df_reduced_2 = english_df_reduced.iloc[[3,7,10,13,16,19,22,25,28,31,34,37]]
less_than_well_speakers = english_df_reduced_2.sum().values.tolist() 
df['P_limited_eng'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(less_than_well_speakers, total_speakers)] # Add % Limited English proficiency Column

In [8]:
# Calculate the Poverty Rate
poverty = unemployment_df[unemployment_df.columns[0::8]].iloc[31].map(lambda x: int(x.replace(',',"")) if isinstance(x, str) else x).tolist()
no_poverty = unemployment_df[unemployment_df.columns[0::8]].iloc[32].map(lambda x: int(x.replace(',',"")) if isinstance(x, str) else x).tolist()
total_pop = [sum(x) for x in zip(no_poverty, poverty)]
df['Poverty_rate'] = [np.nan if x[1] == 0 else x[0]/x[1] for x in zip(poverty, total_pop)]

In [9]:
# Calculate the Percent limited english
df['MED_HH_income'] = HH_df[HH_df.columns[0::8]].iloc[11].values.tolist()
df['MED_HH_income'] = df['MED_HH_income'].replace('-',np.nan).map(lambda x: int(x.replace(',',"")) if isinstance(x, str) else x)

In [10]:
# Calculate Unemployment rate
df['UE_rate'] = unemployment_df[unemployment_df.columns[6::8]].iloc[0].values.tolist()
df['UE_rate'] = df['UE_rate'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

In [11]:
# Calculate Uninsured
df['P_UI'] = insured_df[insured_df.columns[8::10]].iloc[0].values.tolist()
df['P_UI'] = df['P_UI'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

# Calculate Insured
df['P_Insured'] = insured_df[insured_df.columns[4::10]].iloc[0].values.tolist()
df['P_Insured'] = df['P_Insured'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

# Calculate Uninsured under 18
df['P_UI_under_18'] = insured_df[insured_df.columns[8::10]].iloc[11].values.tolist()
df['P_UI_under_18'] = df['P_UI_under_18'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

# Calculate Uninsured  19-64
df['P_UI_18-64'] = insured_df[insured_df.columns[8::10]].iloc[12].values.tolist()
df['P_UI_18-64'] = df['P_UI_18-64'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

# Calculate Uninsured  over 64
df['P_UI_65_over'] = insured_df[insured_df.columns[8::10]].iloc[13].values.tolist()
df['P_UI_65_over'] = df['P_UI_65_over'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

In [12]:
# Calculate Private insurance percentage
df['P_any_private_ins'] = private_insurance_df[private_insurance_df.columns[4::6]].iloc[0].values.tolist()
df['P_any_private_ins'] = df['P_any_private_ins'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

In [13]:
# Calculate Public insurance percentage
df['P_any_public_ins'] = public_insurance_df[public_insurance_df.columns[4::6]].iloc[0].values.tolist()
df['P_any_public_ins'] = df['P_any_public_ins'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

# Calculate Medicare Alone percentage
df['P_Medicare_alone'] = public_insurance_df[public_insurance_df.columns[4::6]].iloc[2].values.tolist()
df['P_Medicare_alone'] = df['P_Medicare_alone'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

# Calculate Medicaid Alone percentage
df['P_Medicaid_alone'] = public_insurance_df[public_insurance_df.columns[4::6]].iloc[6].values.tolist()
df['P_Medicaid_alone'] = df['P_Medicaid_alone'].replace('-',np.nan).map(lambda x: float(x.strip('%'))/100 if isinstance(x, str) else x)

In [14]:
df

,FIPS,Total_population,P_WH,P_AA,P_AI,P_AS,P_NH,P_OR,P_2R,P_Latino,...,UE_rate,P_UI,P_Insured,P_UI_under_18,P_UI_18-64,P_UI_65_over,P_any_private_ins,P_any_public_ins,P_Medicare_alone,P_Medicaid_alone
0,49001100100,3322,0.973209,0.000000,0.015051,0.000000,0.000000,0.011740,0.000000,0.094521,...,0.034,0.110,0.890,0.068,0.176,0.000,0.739,0.271,0.184,0.109
1,49001100200,3121,0.944569,0.000000,0.003845,0.005127,0.000000,0.038449,0.008010,0.132970,...,0.049,0.132,0.868,0.178,0.132,0.000,0.787,0.199,0.134,0.071
2,49003960100,2989,0.977250,0.004349,0.002676,0.006357,0.000000,0.006691,0.002676,0.036467,...,0.020,0.094,0.906,0.106,0.114,0.000,0.777,0.222,0.163,0.068
3,49003960200,7947,0.966277,0.000881,0.010318,0.008305,0.001636,0.008179,0.004404,0.100793,...,0.049,0.049,0.951,0.041,0.064,0.000,0.818,0.230,0.116,0.115
4,49003960300,8810,0.874801,0.019864,0.000000,0.018388,0.000000,0.057548,0.029398,0.157435,...,0.058,0.073,0.927,0.034,0.115,0.022,0.752,0.229,0.094,0.148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,49057210900,7005,0.924197,0.018558,0.005996,0.000000,0.000000,0.005139,0.046110,0.117773,...,0.027,0.072,0.928,0.043,0.098,0.028,0.838,0.197,0.159,0.040
584,49057211000,3244,0.953144,0.009864,0.000000,0.016030,0.000000,0.000000,0.020962,0.149507,...,0.084,0.101,0.899,0.032,0.154,0.000,0.808,0.203,0.137,0.078
585,49057211100,5367,0.921558,0.001304,0.000000,0.003913,0.000000,0.002422,0.070803,0.058506,...,0.048,0.068,0.932,0.053,0.095,0.000,0.772,0.316,0.180,0.156
586,49057211201,4820,0.940664,0.008714,0.000000,0.007469,0.001660,0.024274,0.017220,0.076763,...,0.043,0.116,0.884,0.100,0.150,0.000,0.790,0.197,0.153,0.067
587,49057211202,6772,0.957767,0.003692,0.000738,0.006054,0.005907,0.003101,0.022741,0.050059,...,0.011,0.092,0.908,0.060,0.138,0.000,0.817,0.265,0.224,0.071